/// content_l10n.dart
/// GENERATED by tool/gen_content_l10n.py -- do not hand-edit.
///
/// Maps content-catalogue ids (artifacts, achievements, items, tiles)
/// to their localized names and descriptions.
///
/// The definitions in lib/game/ keep their English text: those layers
/// have no BuildContext, and the id must stay locale-independent so it
/// can be saved and compared. These resolvers translate at render time
/// and fall back to that English for any unknown id.

import '../l10n/app_localizations.dart';

/// Localized name for a ArtifactDefinition id.
///
/// [fallback] is the definition's own English text, returned
/// for any id without a key (e.g. content added since the
/// last l10n pass).
String localizedArtifactName(
    AppLocalizations l10n, String id, String fallback) {
  switch (id) {
    case 'ts_fossil_fern':
      return l10n.artifactTsFossilFern;
    case 'ts_old_boot':
      return l10n.artifactTsOldBoot;
    case 'ts_clay_jar':
      return l10n.artifactTsClayJar;
    case 'ts_arrowhead':
      return l10n.artifactTsArrowhead;
    case 'ts_coin_hoard':
      return l10n.artifactTsCoinHoard;
    case 'pf_mammoth_tusk':
      return l10n.artifactPfMammothTusk;
    case 'pf_ice_lens':
      return l10n.artifactPfIceLens;
    case 'pf_frozen_flower':
      return l10n.artifactPfFrozenFlower;
    case 'pf_sled_runner':
      return l10n.artifactPfSledRunner;
    case 'pf_amber_insect':
      return l10n.artifactPfAmberInsect;
    case 'cc_singing_geode':
      return l10n.artifactCcSingingGeode;
    case 'cc_prism_core':
      return l10n.artifactCcPrismCore;
    case 'cc_petrified_eye':
      return l10n.artifactCcPetrifiedEye;
    case 'cc_resonant_shard':
      return l10n.artifactCcResonantShard;
    case 'cc_hollow_bell':
      return l10n.artifactCcHollowBell;
    case 'mc_obsidian_blade':
      return l10n.artifactMcObsidianBlade;
    case 'mc_fire_opal':
      return l10n.artifactMcFireOpal;
    case 'mc_basalt_idol':
      return l10n.artifactMcBasaltIdol;
    case 'mc_meteor_fragment':
      return l10n.artifactMcMeteorFragment;
    case 'mc_heart_of_core':
      return l10n.artifactMcHeartOfCore;
  }
  return fallback;
}

/// Localized description for a ArtifactDefinition id.
///
/// [fallback] is the definition's own English text, returned
/// for any id without a key (e.g. content added since the
/// last l10n pass).
String localizedArtifactDescription(
    AppLocalizations l10n, String id, String fallback) {
  switch (id) {
    case 'ts_fossil_fern':
      return l10n.artifactTsFossilFernDesc;
    case 'ts_old_boot':
      return l10n.artifactTsOldBootDesc;
    case 'ts_clay_jar':
      return l10n.artifactTsClayJarDesc;
    case 'ts_arrowhead':
      return l10n.artifactTsArrowheadDesc;
    case 'ts_coin_hoard':
      return l10n.artifactTsCoinHoardDesc;
    case 'pf_mammoth_tusk':
      return l10n.artifactPfMammothTuskDesc;
    case 'pf_ice_lens':
      return l10n.artifactPfIceLensDesc;
    case 'pf_frozen_flower':
      return l10n.artifactPfFrozenFlowerDesc;
    case 'pf_sled_runner':
      return l10n.artifactPfSledRunnerDesc;
    case 'pf_amber_insect':
      return l10n.artifactPfAmberInsectDesc;
    case 'cc_singing_geode':
      return l10n.artifactCcSingingGeodeDesc;
    case 'cc_prism_core':
      return l10n.artifactCcPrismCoreDesc;
    case 'cc_petrified_eye':
      return l10n.artifactCcPetrifiedEyeDesc;
    case 'cc_resonant_shard':
      return l10n.artifactCcResonantShardDesc;
    case 'cc_hollow_bell':
      return l10n.artifactCcHollowBellDesc;
    case 'mc_obsidian_blade':
      return l10n.artifactMcObsidianBladeDesc;
    case 'mc_fire_opal':
      return l10n.artifactMcFireOpalDesc;
    case 'mc_basalt_idol':
      return l10n.artifactMcBasaltIdolDesc;
    case 'mc_meteor_fragment':
      return l10n.artifactMcMeteorFragmentDesc;
    case 'mc_heart_of_core':
      return l10n.artifactMcHeartOfCoreDesc;
  }
  return fallback;
}

/// Localized name for a AchievementDefinition id.
///
/// [fallback] is the definition's own English text, returned
/// for any id without a key (e.g. content added since the
/// last l10n pass).
String localizedAchievementName(
    AppLocalizations l10n, String id, String fallback) {
  switch (id) {
    case 'ore_10':
      return l10n.achievementOre10;
    case 'ore_100':
      return l10n.achievementOre100;
    case 'ore_500':
      return l10n.achievementOre500;
    case 'ore_2000':
      return l10n.achievementOre2000;
    case 'ore_10000':
      return l10n.achievementOre10000;
    case 'depth_50':
      return l10n.achievementDepth50;
    case 'depth_120':
      return l10n.achievementDepth120;
    case 'depth_240':
      return l10n.achievementDepth240;
    case 'depth_360':
      return l10n.achievementDepth360;
    case 'depth_445':
      return l10n.achievementDepth445;
    case 'cash_1k':
      return l10n.achievementCash1k;
    case 'cash_25k':
      return l10n.achievementCash25k;
    case 'cash_250k':
      return l10n.achievementCash250k;
    case 'cash_1m':
      return l10n.achievementCash1m;
    case 'level_5':
      return l10n.achievementLevel5;
    case 'level_10':
      return l10n.achievementLevel10;
    case 'level_18':
      return l10n.achievementLevel18;
    case 'level_25':
      return l10n.achievementLevel25;
    case 'artifact_1':
      return l10n.achievementArtifact1;
    case 'artifact_10':
      return l10n.achievementArtifact10;
    case 'artifact_20':
      return l10n.achievementArtifact20;
    case 'blast_5':
      return l10n.achievementBlast5;
    case 'blast_50':
      return l10n.achievementBlast50;
    case 'sales_10':
      return l10n.achievementSales10;
    case 'sales_100':
      return l10n.achievementSales100;
    case 'death_1':
      return l10n.achievementDeath1;
    case 'death_25':
      return l10n.achievementDeath25;
  }
  return fallback;
}

/// Localized description for a AchievementDefinition id.
///
/// [fallback] is the definition's own English text, returned
/// for any id without a key (e.g. content added since the
/// last l10n pass).
String localizedAchievementDescription(
    AppLocalizations l10n, String id, String fallback) {
  switch (id) {
    case 'ore_10':
      return l10n.achievementOre10Desc;
    case 'ore_100':
      return l10n.achievementOre100Desc;
    case 'ore_500':
      return l10n.achievementOre500Desc;
    case 'ore_2000':
      return l10n.achievementOre2000Desc;
    case 'ore_10000':
      return l10n.achievementOre10000Desc;
    case 'depth_50':
      return l10n.achievementDepth50Desc;
    case 'depth_120':
      return l10n.achievementDepth120Desc;
    case 'depth_240':
      return l10n.achievementDepth240Desc;
    case 'depth_360':
      return l10n.achievementDepth360Desc;
    case 'depth_445':
      return l10n.achievementDepth445Desc;
    case 'cash_1k':
      return l10n.achievementCash1kDesc;
    case 'cash_25k':
      return l10n.achievementCash25kDesc;
    case 'cash_250k':
      return l10n.achievementCash250kDesc;
    case 'cash_1m':
      return l10n.achievementCash1mDesc;
    case 'level_5':
      return l10n.achievementLevel5Desc;
    case 'level_10':
      return l10n.achievementLevel10Desc;
    case 'level_18':
      return l10n.achievementLevel18Desc;
    case 'level_25':
      return l10n.achievementLevel25Desc;
    case 'artifact_1':
      return l10n.achievementArtifact1Desc;
    case 'artifact_10':
      return l10n.achievementArtifact10Desc;
    case 'artifact_20':
      return l10n.achievementArtifact20Desc;
    case 'blast_5':
      return l10n.achievementBlast5Desc;
    case 'blast_50':
      return l10n.achievementBlast50Desc;
    case 'sales_10':
      return l10n.achievementSales10Desc;
    case 'sales_100':
      return l10n.achievementSales100Desc;
    case 'death_1':
      return l10n.achievementDeath1Desc;
    case 'death_25':
      return l10n.achievementDeath25Desc;
  }
  return fallback;
}

/// Localized name for a ItemType name.
///
/// [fallback] is the definition's own English text, returned
/// for any id without a key (e.g. content added since the
/// last l10n pass).
String localizedItemName(
    AppLocalizations l10n, String id, String fallback) {
  switch (id) {
    case 'backupFuel':
      return l10n.itemBackupFuel;
    case 'repairBot':
      return l10n.itemRepairBot;
    case 'dynamite':
      return l10n.itemDynamite;
    case 'c4':
      return l10n.itemC4;
    case 'spaceRift':
      return l10n.itemSpaceRift;
    case 'oreScanner':
      return l10n.itemOreScanner;
    case 'heatShield':
      return l10n.itemHeatShield;
    case 'backupFuel':
      return l10n.itemBackupFuel;
    case 'repairBot':
      return l10n.itemRepairBot;
    case 'dynamite':
      return l10n.itemDynamite;
    case 'c4':
      return l10n.itemC4;
    case 'spaceRift':
      return l10n.itemSpaceRift;
    case 'oreScanner':
      return l10n.itemOreScanner;
    case 'heatShield':
      return l10n.itemHeatShield;
    case 'backupFuel':
      return l10n.itemBackupFuel;
    case 'repairBot':
      return l10n.itemRepairBot;
    case 'dynamite':
      return l10n.itemDynamite;
    case 'c4':
      return l10n.itemC4;
    case 'spaceRift':
      return l10n.itemSpaceRift;
    case 'oreScanner':
      return l10n.itemOreScanner;
    case 'heatShield':
      return l10n.itemHeatShield;
  }
  return fallback;
}

/// Localized name for a TileType name.
///
/// [fallback] is the definition's own English text, returned
/// for any id without a key (e.g. content added since the
/// last l10n pass).
String localizedTileName(
    AppLocalizations l10n, String id, String fallback) {
  switch (id) {
    case 'empty':
      return l10n.tileEmpty;
    case 'dirt':
      return l10n.tileDirt;
    case 'rock':
      return l10n.tileRock;
    case 'coal':
      return l10n.tileCoal;
    case 'copper':
      return l10n.tileCopper;
    case 'silver':
      return l10n.tileSilver;
    case 'gold':
      return l10n.tileGold;
    case 'sapphire':
      return l10n.tileSapphire;
    case 'emerald':
      return l10n.tileEmerald;
    case 'ruby':
      return l10n.tileRuby;
    case 'diamond':
      return l10n.tileDiamond;
    case 'lava':
      return l10n.tileLava;
    case 'gas':
      return l10n.tileGas;
    case 'frozenDirt':
      return l10n.tileFrozenDirt;
    case 'magmaRock':
      return l10n.tileMagmaRock;
    case 'crystalOre':
      return l10n.tileCrystalOre;
    case 'unstableRock':
      return l10n.tileUnstableRock;
    case 'lootCrate':
      return l10n.tileLootCrate;
    case 'artifact':
      return l10n.tileArtifact;
    case 'bedrock':
      return l10n.tileBedrock;
  }
  return fallback;
}

/// Localized display name for a [GearRarity].
///
/// Hand-maintained (the enum is small and stable) rather than generated
/// with the catalogue above.
String localizedRarity(AppLocalizations l10n, String rarityName,
    String fallback) {
  switch (rarityName) {
    case 'common':
      return l10n.rarityCommon;
    case 'uncommon':
      return l10n.rarityUncommon;
    case 'rare':
      return l10n.rarityRare;
    case 'epic':
      return l10n.rarityEpic;
    case 'legendary':
      return l10n.rarityLegendary;
  }
  return fallback;
}
