/// streak_glyph.dart
/// Animated flame shown next to the login streak on the Account screen.
///
/// The asset is a hand-authored dotLottie generated by
/// `tool/gen_streak_glyph.py`. Its timeline holds three 30-frame
/// intensity stages; this widget plays the segment matching the
/// player's streak rather than tweening one generic animation, so the
/// flame visibly grows and brightens as the streak climbs.
///
/// Keep [StreakStage] in sync with STAGES in the generator.
///
/// dotlottie_flutter renders through a native platform view, which is
/// unavailable in widget tests and on unsupported platforms — the
/// widget falls back to the original emoji whenever the animation can't
/// load, so the UI is never blank.

import 'package:dotlottie_flutter/dotlottie_flutter.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;

import '../game/systems/streak_system.dart';

/// One 30-frame stage of the generated timeline.
enum StreakStage {
  ember(segment: [0, 30], emoji: '📅'),
  burning(segment: [30, 60], emoji: '📅'),
  blaze(segment: [60, 90], emoji: '🔥');

  const StreakStage({required this.segment, required this.emoji});

  /// [startFrame, endFrame] in the generated animation.
  final List<int> segment;

  /// Shown when the animation can't render.
  final String emoji;

  /// Stage for a streak, given the jackpot rung of the active ladder.
  /// Below a third of the way it's an ember, at or past the jackpot a
  /// blaze, in between it's burning.
  static StreakStage forStreak(int streak, int jackpotAt) {
    if (jackpotAt <= 0) return StreakStage.ember;
    if (streak >= jackpotAt) return StreakStage.blaze;
    if (streak <= (jackpotAt / 3).ceil()) return StreakStage.ember;
    return StreakStage.burning;
  }
}

class StreakGlyph extends StatefulWidget {
  /// Current streak day (0 = no active streak).
  final int streak;

  /// Rungs in the active ladder — the jackpot threshold. Defaults to the
  /// compiled-in ladder length.
  final int ladderLength;

  final double size;

  const StreakGlyph({
    super.key,
    required this.streak,
    this.ladderLength = 0,
    this.size = 34,
  });

  /// Bundle key for the generated animation, as declared in pubspec.
  static const String assetKey = 'assets/animations/streak_glyph.lottie';

  /// What to hand dotlottie_flutter: [assetKey] with the leading
  /// `assets/` removed, because the plugin prepends that itself. Passing
  /// the full key resolves to `assets/assets/...`, which renders an
  /// empty box and never fires `onLoadError`.
  static const String assetSource = 'animations/streak_glyph.lottie';

  @override
  State<StreakGlyph> createState() => _StreakGlyphState();
}

class _StreakGlyphState extends State<StreakGlyph> {
  /// Skips the platform view entirely. Widget tests can't host one, so
  /// they would otherwise hit the native channel and hang or throw.
  @visibleForTesting
  static bool debugDisableAnimation = false;

  /// null = still checking, true = usable, false = fall back to emoji.
  bool? _assetOk;

  @override
  void initState() {
    super.initState();
    _verifyAsset();
  }

  /// Confirm the animation is actually in the bundle before handing it
  /// to the player.
  ///
  /// The plugin catches asset-load failures internally and only
  /// debugPrints them — `onLoadError` never fires for a missing or
  /// unreadable asset — so relying on that callback leaves an empty
  /// box on screen with no fallback. Checking here is the only way to
  /// make the fallback dependable.
  Future<void> _verifyAsset() async {
    if (debugDisableAnimation || !_supportsPlatformView) {
      if (mounted) setState(() => _assetOk = false);
      return;
    }
    try {
      await rootBundle.load(StreakGlyph.assetKey);
      if (mounted) setState(() => _assetOk = true);
    } catch (e) {
      debugPrint('StreakGlyph: ${StreakGlyph.assetKey} unavailable, using emoji: $e');
      if (mounted) setState(() => _assetOk = false);
    }
  }

  int get _jackpotAt => widget.ladderLength > 0
      ? widget.ladderLength
      : StreakSystem.defaultRewardLadder.length;

  StreakStage get _stage => StreakStage.forStreak(widget.streak, _jackpotAt);

  @override
  Widget build(BuildContext context) {
    final stage = _stage;

    // Emoji covers the not-yet-verified frame too, so the glyph is
    // never an empty box even for the first frame after mount.
    if (_assetOk != true) {
      return SizedBox(
        width: widget.size,
        height: widget.size,
        child: Center(
          child: Text(stage.emoji,
              style: TextStyle(fontSize: widget.size * 0.8)),
        ),
      );
    }

    return SizedBox(
      width: widget.size,
      height: widget.size,
      child: DotLottieView(
        // Key by stage so switching segments rebuilds the player rather
        // than leaving it parked on the previous range.
        key: ValueKey(stage),
        source: StreakGlyph.assetSource,
        sourceType: 'asset',
        autoplay: true,
        loop: true,
        segment: stage.segment,
        useFrameInterpolation: true,
        fit: BoxFit.contain,
        onLoadError: () {
          if (mounted) setState(() => _assetOk = false);
        },
      ),
    );
  }

  static bool get _supportsPlatformView {
    if (kIsWeb) return true;
    return defaultTargetPlatform == TargetPlatform.android ||
        defaultTargetPlatform == TargetPlatform.iOS ||
        defaultTargetPlatform == TargetPlatform.macOS ||
        defaultTargetPlatform == TargetPlatform.windows ||
        defaultTargetPlatform == TargetPlatform.linux;
  }
}
