/// streak_glyph.dart
/// Animated flame shown next to the login streak on the Account screen.
///
/// The asset is a hand-authored Lottie generated by
/// `tool/gen_streak_glyph.py`. Its timeline holds three 30-frame
/// intensity stages; this widget loops only the range matching the
/// player's streak, so the flame visibly grows and brightens as the
/// streak climbs rather than tweening one generic animation.
///
/// Keep [StreakStage] in sync with STAGES in the generator.
///
/// Rendering is pure Dart, so a failure surfaces as an exception we can
/// catch rather than an empty box — but the emoji fallback stays as a
/// backstop for a missing or unparsable asset.

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';

import '../game/systems/streak_system.dart';

/// One 30-frame stage of the generated timeline.
enum StreakStage {
  ember(segment: [0, 30], emoji: '📅'),
  burning(segment: [30, 60], emoji: '📅'),
  blaze(segment: [60, 90], emoji: '🔥');

  const StreakStage({required this.segment, required this.emoji});

  /// [startFrame, endFrame] in the generated animation.
  final List<int> segment;

  /// Shown when the animation can't render.
  final String emoji;

  /// Stage for a streak, given the jackpot rung of the active ladder.
  /// Below a third of the way it's an ember, at or past the jackpot a
  /// blaze, in between it's burning.
  static StreakStage forStreak(int streak, int jackpotAt) {
    if (jackpotAt <= 0) return StreakStage.ember;
    if (streak >= jackpotAt) return StreakStage.blaze;
    if (streak <= (jackpotAt / 3).ceil()) return StreakStage.ember;
    return StreakStage.burning;
  }
}

class StreakGlyph extends StatefulWidget {
  /// Current streak day (0 = no active streak).
  final int streak;

  /// Rungs in the active ladder — the jackpot threshold. Defaults to the
  /// compiled-in ladder length.
  final int ladderLength;

  final double size;

  const StreakGlyph({
    super.key,
    required this.streak,
    this.ladderLength = 0,
    this.size = 34,
  });

  /// Bundle key for the generated animation, as declared in pubspec.
  static const String assetKey = 'assets/animations/streak_glyph.json';

  /// Renders the emoji instead of the animation. Lets widget tests avoid
  /// pumping a repeating animation that never settles.
  @visibleForTesting
  static bool debugDisableAnimation = false;

  @override
  State<StreakGlyph> createState() => StreakGlyphState();
}

class StreakGlyphState extends State<StreakGlyph>
    with SingleTickerProviderStateMixin {
  /// Constructed eagerly in initState, NOT as a lazy `late final`: on the
  /// emoji-only path nothing would touch it until dispose(), and building
  /// a Ticker there looks up an ancestor on an already-deactivated
  /// widget.
  late final AnimationController _controller;

  LottieComposition? _composition;
  bool _failed = false;
  StreakStage? _playingStage;

  /// Stage whose frame range is currently looping, or null before the
  /// composition loads. Exposed so tests can catch the range failing to
  /// follow a stage change — the rendered glyph alone would not show it,
  /// since build() always reads the current stage.
  @visibleForTesting
  StreakStage? get playingStage => _playingStage;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(vsync: this);
  }

  /// Resolved per-widget, so [didUpdateWidget] can compare the old and
  /// new stages using each one's OWN ladder length. Reading the current
  /// widget's length for both sides would miss a stage change caused by
  /// the ladder itself changing size — which is exactly what happens
  /// when a server-tuned ladder arrives.
  static StreakStage _stageOf(StreakGlyph w) => StreakStage.forStreak(
        w.streak,
        w.ladderLength > 0
            ? w.ladderLength
            : StreakSystem.defaultRewardLadder.length,
      );

  StreakStage get _stage => _stageOf(widget);

  @override
  void didUpdateWidget(StreakGlyph oldWidget) {
    super.didUpdateWidget(oldWidget);
    // A streak (or ladder) crossing a stage boundary changes which range
    // should loop.
    if (_stageOf(widget) != _stageOf(oldWidget)) {
      _playStage();
    }
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  void _onLoaded(LottieComposition composition) {
    _composition = composition;
    _controller.duration = composition.duration;
    _playStage();
  }

  /// Loop just this stage's frame range.
  ///
  /// AnimationController works in 0..1 over the whole timeline, so the
  /// frame bounds become fractions and the period is scaled to the
  /// slice — otherwise a third of the timeline would play in the time
  /// meant for all of it, i.e. at triple speed.
  void _playStage() {
    final composition = _composition;
    if (composition == null) return;

    final totalFrames = composition.endFrame - composition.startFrame;
    if (totalFrames <= 0 || composition.duration == Duration.zero) return;

    final stage = _stage;
    final min =
        ((stage.segment[0] - composition.startFrame) / totalFrames)
            .clamp(0.0, 1.0);
    final max =
        ((stage.segment[1] - composition.startFrame) / totalFrames)
            .clamp(0.0, 1.0);
    if (max <= min) return;

    _playingStage = stage;
    _controller.repeat(
      min: min,
      max: max,
      period: composition.duration * (max - min),
    );
  }

  @override
  Widget build(BuildContext context) {
    final stage = _stage;

    if (_failed || StreakGlyph.debugDisableAnimation) {
      return _emoji(stage);
    }

    return SizedBox(
      width: widget.size,
      height: widget.size,
      child: Lottie.asset(
        StreakGlyph.assetKey,
        controller: _controller,
        onLoaded: _onLoaded,
        fit: BoxFit.contain,
        // Covers the frame or two before the composition resolves, so
        // the glyph is never an empty box.
        frameBuilder: (context, child, composition) =>
            composition == null ? _emoji(stage) : child,
        errorBuilder: (context, error, stackTrace) {
          debugPrint('StreakGlyph: ${StreakGlyph.assetKey} failed: $error');
          // Can't setState during build; flip after this frame so later
          // rebuilds skip the loader entirely.
          WidgetsBinding.instance.addPostFrameCallback((_) {
            if (mounted && !_failed) setState(() => _failed = true);
          });
          return _emoji(stage);
        },
      ),
    );
  }

  Widget _emoji(StreakStage stage) => SizedBox(
        width: widget.size,
        height: widget.size,
        child: Center(
          child: Text(stage.emoji,
              style: TextStyle(fontSize: widget.size * 0.8)),
        ),
      );
}
