/// surface_layout.dart
/// Where the surface buildings stand, and their bedrock floors.
///
/// Flame-free on purpose: it runs inside the world-generation isolate and
/// in unit tests. The art lives in gear_sprites.dart (BuildingSheet), the
/// rendering in surface_buildings.dart, the entering in DiggleGame.
///
/// Pads are applied AFTER WorldGenerator, never inside it, so generation
/// tests and the pinned blast goldens are untouched. They sit at fixed
/// columns, so every weekly-challenge world is still identical.
library;

import 'tile.dart';
import 'world_generator.dart' show WorldConfig;

/// Order matches the columns of BuildingSheet (generated by sprites.py).
enum BuildingType { shop, store, quests, museum }

class BuildingSite {
  final BuildingType type;

  /// Leftmost tile column of the building.
  final int left;

  const BuildingSite(this.type, this.left);

  /// Footprint in tiles. Must match BuildingSheet.tilesWide (pinned by a
  /// test — the art's doorway is drawn for exactly this width).
  static const int width = 4;

  int get right => left + width - 1;

  /// The doorway is the two middle columns; parking there enters.
  int get doorLeft => left + 1;
  int get doorRight => left + 2;
  bool isDoor(int gridX) => gridX >= doorLeft && gridX <= doorRight;

  /// The bedrock floor: the footprint plus a one-tile apron each side, so
  /// holding down in (or next to) a doorway can never dig.
  int get padLeft => left - 1;
  int get padRight => right + 1;
}

class SurfaceLayout {
  SurfaceLayout._();

  /// Each building's left column, relative to the world centre (the spawn
  /// column). The Shop is nearest — it is the most-used — and the columns
  /// either side of spawn stay open for the starting shaft.
  static const Map<BuildingType, int> _leftFromCentre = {
    BuildingType.museum: -14,
    BuildingType.quests: -8,
    BuildingType.shop: 3,
    BuildingType.store: 9,
  };

  /// Narrowest world the layout fits in (every pad in bounds).
  static const int minWorldWidth = 32;

  /// Building sites for a world [worldWidth] tiles wide, left to right.
  /// Empty when the world is too narrow to hold them.
  static List<BuildingSite> sites(int worldWidth) {
    if (worldWidth < minWorldWidth) return const [];
    final centre = worldWidth ~/ 2;
    return [
      for (final entry in _leftFromCentre.entries)
        BuildingSite(entry.key, centre + entry.value),
    ]..sort((a, b) => a.left.compareTo(b.left));
  }

  /// The building whose doorway is [gridX], if any.
  static BuildingType? doorAt(int worldWidth, int gridX) {
    for (final site in sites(worldWidth)) {
      if (site.isDoor(gridX)) return site.type;
    }
    return null;
  }

  /// Whether (x, y) is part of a building's bedrock floor.
  static bool isPad(WorldConfig config, int x, int y) {
    if (y != config.surfaceRows) return false;
    for (final site in sites(config.width)) {
      if (x >= site.padLeft && x <= site.padRight) return true;
    }
    return false;
  }

  /// Turn every floor tile into revealed bedrock. Idempotent, and safe on
  /// a restored save (an old world gets its floors the first time it loads).
  static void applyPads(List<List<Tile>> grid, WorldConfig config) {
    final y = config.surfaceRows;
    if (grid.isEmpty || y >= grid.first.length) return;
    for (final site in sites(config.width)) {
      for (int x = site.padLeft; x <= site.padRight; x++) {
        if (x < 0 || x >= grid.length) continue;
        final tile = grid[x][y];
        tile.resetDig();
        tile.type = TileType.bedrock;
        tile.isRevealed = true;
      }
    }
  }
}
