/// gear_sprites.dart — GENERATED by DiggleAssets/svgart/sprites.py. Do not
/// hand-edit; regenerate instead.
///
/// Cell lookup for assets/images/DiggleGearSpriteSheet.png (32px cells,
/// 5 rarities x 4 animation frames = 20 columns,
/// 10 rows = slot x view).
/// Side cells face RIGHT (mirror for left); down cells rotate 180 for up.
library;

import 'gear_system.dart' show GearSlot, GearRarity;

class GearSpriteSheet {
  static const String asset = 'DiggleGearSpriteSheet.png';
  static const double cellSize = 32.0;

  /// Animation frames per rarity. Rarity selects the art; the caller's
  /// action state selects the playback rate. Frame 0 is authored as the
  /// shortest thruster plume, so clamping to frames 0-1 reads as idle.
  static const int frames = 4;

  /// Sheet dimensions in cells. Callers keying a cache by (col, row) must
  /// use [columns] as the stride — a hardcoded one collides silently.
  static const int columns = 20;
  static const int rows = 10;

  /// Pixel width of the sheet. Assert the loaded image matches this — a
  /// stale generated Dart against a new PNG otherwise shows up only as an
  /// invisible or silently static drill.
  static const double sheetWidth = 640.0;
  static const double sheetHeight = 320.0;

  /// Painter's order — matches the NFT reveal compositor.
  static const List<GearSlot> drawOrder = [
    GearSlot.hull,
    GearSlot.fuelTank,
    GearSlot.thruster,
    GearSlot.drill,
    GearSlot.cargoHold,
  ];

  static const Map<GearSlot, int> _sideRow = {
    GearSlot.hull: 0,
    GearSlot.thruster: 1,
    GearSlot.fuelTank: 2,
    GearSlot.drill: 3,
    GearSlot.cargoHold: 4,
  };

  /// (column, row) of a cell. [down] false = side view.
  ///
  /// [frame] defaults to 0, so every pre-animation call site keeps
  /// compiling and keeps rendering exactly what it rendered before.
  static (int, int) cell(
    GearSlot slot,
    GearRarity rarity, {
    bool down = false,
    int frame = 0,
  }) {
    final row = _sideRow[slot]! + (down ? 5 : 0);
    return (rarity.index * frames + frame, row);
  }

  /// 512px transparent preview art for hangar/shop UI, keyed by the
  /// NFT trait value (part name, case-insensitive).
  static const Map<String, String> _previewFile = {
    'standard prospector': 'hull_standard_prospector',
    'rusty hauler': 'hull_rusty_hauler',
    'armored vanguard': 'hull_armored_vanguard',
    'cyber scarab': 'hull_cyber_scarab',
    'golden behemoth': 'hull_golden_behemoth',
    'ghost stealth': 'hull_ghost_stealth',
    'ion drive': 'thruster_ion_drive',
    'turbo fan': 'thruster_turbo_fan',
    'chemical burner': 'thruster_chemical_burner',
    'plasma jet': 'thruster_plasma_jet',
    'gravity well': 'thruster_gravity_well',
    'quantum glitch': 'thruster_quantum_glitch',
    'diesel canister': 'fuel_diesel_canister',
    'oil drum': 'fuel_oil_drum',
    'hydrogen cell': 'fuel_hydrogen_cell',
    'nuclear battery': 'fuel_nuclear_battery',
    'dark matter vial': 'fuel_dark_matter_vial',
    'miniature star': 'fuel_miniature_star',
    'steel augur': 'drill_steel_augur',
    'iron pike': 'drill_iron_pike',
    'tungsten breaker': 'drill_tungsten_breaker',
    'laser bore': 'drill_laser_bore',
    'sonic pulverizer': 'drill_sonic_pulverizer',
    'diamond omni-drill': 'drill_diamond_omni',
    'standard bin': 'cargo_standard_bin',
    'scrap basket': 'cargo_scrap_basket',
    'reinforced crate': 'cargo_reinforced_crate',
    'ore net': 'cargo_ore_net',
    'cryo pod': 'cargo_cryo_pod',
    'dimensional vault': 'cargo_dimensional_vault',
  };

  static String? previewAsset(String partName) {
    final file = _previewFile[partName.toLowerCase().trim()];
    return file == null ? null : 'assets/images/gear/$file.png';
  }
}

/// The free starter machine, for players without a complete NFT.
///
/// Pre-composited rather than layered: there is exactly one of it, so there
/// is nothing to mix and match. Same 4-frame band machinery as the gear
/// sheet — the caller passes the frame it already computed.
///
/// Authored deliberately worse than Common (one thruster pod, stubby drill,
/// no cargo hold) so equipping any NFT is a visible upgrade.
class BaseDrillSheet {
  /// Lives in assets/images/gear/, which pubspec already declares as a
  /// DIRECTORY, so adding this needed no pubspec change. Flame's default
  /// prefix is assets/images/.
  static const String asset = 'gear/DiggleDrillSheet.png';
  static const double cellSize = 32.0;

  static const int frames = 4;
  static const int columns = 4;
  static const int rows = 2;
  static const double sheetWidth = 128.0;
  static const double sheetHeight = 64.0;

  /// (column, row). Row 0 = side view, facing RIGHT (mirror for left);
  /// row 1 = down view (rotate 180 for flying up).
  static (int, int) cell({bool down = false, int frame = 0}) =>
      (frame, down ? 1 : 0);
}
