/// gear_sprites.dart — GENERATED by DiggleAssets/svgart/sprites.py. Do not
/// hand-edit; regenerate instead.
///
/// Cell lookup for assets/images/DiggleGearSpriteSheet.png (32px cells,
/// 5 columns = GearRarity.index, 10 rows = slot x view).
/// Side cells face RIGHT (mirror for left); down cells rotate 180 for up.
library;

import 'gear_system.dart' show GearSlot, GearRarity;

class GearSpriteSheet {
  static const String asset = 'DiggleGearSpriteSheet.png';
  static const double cellSize = 32.0;

  /// Painter's order — matches the NFT reveal compositor.
  static const List<GearSlot> drawOrder = [
    GearSlot.hull,
    GearSlot.fuelTank,
    GearSlot.thruster,
    GearSlot.drill,
    GearSlot.cargoHold,
  ];

  static const Map<GearSlot, int> _sideRow = {
    GearSlot.hull: 0,
    GearSlot.thruster: 1,
    GearSlot.fuelTank: 2,
    GearSlot.drill: 3,
    GearSlot.cargoHold: 4,
  };

  /// (column, row) of a cell. [down] false = side view.
  static (int, int) cell(GearSlot slot, GearRarity rarity, {bool down = false}) {
    final row = _sideRow[slot]! + (down ? 5 : 0);
    return (rarity.index, row);
  }

  /// 512px transparent preview art for hangar/shop UI, keyed by the
  /// NFT trait value (part name, case-insensitive).
  static const Map<String, String> _previewFile = {
    'standard prospector': 'hull_standard_prospector',
    'armored vanguard': 'hull_armored_vanguard',
    'cyber scarab': 'hull_cyber_scarab',
    'golden behemoth': 'hull_golden_behemoth',
    'ghost stealth': 'hull_ghost_stealth',
    'ion drive': 'thruster_ion_drive',
    'chemical burner': 'thruster_chemical_burner',
    'plasma jet': 'thruster_plasma_jet',
    'gravity well': 'thruster_gravity_well',
    'quantum glitch': 'thruster_quantum_glitch',
    'diesel canister': 'fuel_diesel_canister',
    'hydrogen cell': 'fuel_hydrogen_cell',
    'nuclear battery': 'fuel_nuclear_battery',
    'dark matter vial': 'fuel_dark_matter_vial',
    'miniature star': 'fuel_miniature_star',
    'steel augur': 'drill_steel_augur',
    'tungsten breaker': 'drill_tungsten_breaker',
    'laser bore': 'drill_laser_bore',
    'sonic pulverizer': 'drill_sonic_pulverizer',
    'diamond omni-drill': 'drill_diamond_omni',
    'standard bin': 'cargo_standard_bin',
    'reinforced crate': 'cargo_reinforced_crate',
    'ore net': 'cargo_ore_net',
    'cryo pod': 'cargo_cryo_pod',
    'dimensional vault': 'cargo_dimensional_vault',
  };

  static String? previewAsset(String partName) {
    final file = _previewFile[partName.toLowerCase().trim()];
    return file == null ? null : 'assets/images/gear/$file.png';
  }
}
