"""Generate content-catalogue localization from catalogue.json.

Writes the keys into every arb file (English everywhere, per the
translator-placeholder approach) and emits lib/ui/content_l10n.dart with
id-keyed resolvers. Definitions keep their English text, which the
resolvers use as a fallback, so an id we have no key for still renders.
"""
import json
import glob
import re
import sys
import io
from collections import OrderedDict

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8',
                              errors='replace')

cat = json.load(open('tool/catalogue.json', encoding='utf-8'))


def camel(prefix, raw):
    parts = re.split(r'[_\s]+', raw)
    return prefix + ''.join(p[:1].upper() + p[1:] for p in parts if p)


def clean(s):
    """Undo Dart source escaping; arb holds the literal text.

    `\\$` matters: arb has no dollar escape, so leaving the backslash in
    ships a visible one (gen-l10n re-escapes both characters).
    """
    if not s:
        return s
    return (s.replace("\\'", "'").replace('\\"', '"')
             .replace('\\$', '$'))


keys = OrderedDict()
resolvers = []


def build(label, prefix, items, with_desc, fn_name, id_doc):
    name_cases, desc_cases = [], []
    for it in items:
        key = camel(prefix, it['id'])
        keys[key] = clean(it['name'])
        name_cases.append((it['id'], key))
        if with_desc and it.get('desc'):
            dkey = key + 'Desc'
            keys[dkey] = clean(it['desc'])
            desc_cases.append((it['id'], dkey))

    def emit(fname, cases, what):
        body = '\n'.join(
            f"    case '{i}':\n      return l10n.{k};" for i, k in cases)
        return (
            f"/// Localized {what} for a {id_doc}.\n"
            f"///\n"
            f"/// [fallback] is the definition's own English text, returned\n"
            f"/// for any id without a key (e.g. content added since the\n"
            f"/// last l10n pass).\n"
            f"String {fname}(\n"
            f"    AppLocalizations l10n, String id, String fallback) {{\n"
            f"  switch (id) {{\n{body}\n  }}\n"
            f"  return fallback;\n}}\n")

    resolvers.append(emit(fn_name, name_cases, 'name'))
    if desc_cases:
        resolvers.append(
            emit(fn_name.replace('Name', 'Description'), desc_cases,
                 'description'))


build('artifacts', 'artifact', cat['artifacts'], True,
      'localizedArtifactName', 'ArtifactDefinition id')
build('achievements', 'achievement', cat['achievements'], True,
      'localizedAchievementName', 'AchievementDefinition id')
build('items', 'item', cat['items'], True,
      'localizedItemName', 'ItemType name')
build('tiles', 'tile', cat['tiles'], False,
      'localizedTileName', 'TileType name')

# Hand-maintained resolvers, kept here so a regen does not drop them.
resolvers.append('''/// Localized display name for a [GearRarity].
///
/// Hand-maintained (the enum is small and stable) rather than generated
/// from the catalogue above.
String localizedRarity(AppLocalizations l10n, String rarityName,
    String fallback) {
  switch (rarityName) {
    case 'common':
      return l10n.rarityCommon;
    case 'uncommon':
      return l10n.rarityUncommon;
    case 'rare':
      return l10n.rarityRare;
    case 'epic':
      return l10n.rarityEpic;
    case 'legendary':
      return l10n.rarityLegendary;
  }
  return fallback;
}
''')

resolvers.append('''/// Localized display name for a [Biome].
///
/// Hand-maintained: biomeName is a plain field on Biome/ArtifactDefinition
/// rather than a catalogue entry, so the extractor never sees it.
///
/// Values carry their own casing — the museum header renders them as-is
/// instead of calling toUpperCase(), which would be a no-op for ja/ko/zh
/// and takes the choice away from the translator. [fallback] should
/// therefore already be cased for display.
String localizedBiomeName(AppLocalizations l10n, String biomeName,
    String fallback) {
  switch (biomeName) {
    case 'Topsoil':
      return l10n.biomeTopsoil;
    case 'Permafrost':
      return l10n.biomePermafrost;
    case 'Crystal Caverns':
      return l10n.biomeCrystalCaverns;
    case 'Magma Core':
      return l10n.biomeMagmaCore;
  }
  return fallback;
}
''')

# ── arb files ────────────────────────────────────────────────────
for path in sorted(glob.glob('lib/l10n/app_*.arb')):
    data = json.load(open(path, encoding='utf-8'),
                     object_pairs_hook=OrderedDict)
    added = 0
    for k, v in keys.items():
        if k not in data:
            data[k] = v
            added += 1
    json.dump(data, open(path, 'w', encoding='utf-8'),
              ensure_ascii=False, indent=2)
    open(path, 'a', encoding='utf-8').write('\n')
    print(f'{path}: +{added}')

# ── resolver ─────────────────────────────────────────────────────
header = '''/// content_l10n.dart
/// GENERATED by tool/gen_content_l10n.py -- do not hand-edit.
///
/// Maps content-catalogue ids (artifacts, achievements, items, tiles)
/// to their localized names and descriptions, plus the hand-maintained
/// resolvers for gear rarity and biome names.
///
/// The definitions in lib/game/ keep their English text: those layers
/// have no BuildContext, and the id must stay locale-independent so it
/// can be saved and compared. These resolvers translate at render time
/// and fall back to that English for any unknown id.

import '../l10n/app_localizations.dart';

'''
open('lib/ui/content_l10n.dart', 'w', encoding='utf-8').write(
    header + '\n'.join(resolvers))
print(f'\nlib/ui/content_l10n.dart: {len(resolvers)} resolvers, '
      f'{len(keys)} keys')
